<div id="footer">
  <p class="kerned"><a href="/contact/">CONTACT US</a> | <a href="/site-map/">SITE MAP</a> |  <a href="/apply/">APPLY NOW</a> | <span class="uppercase"><a href="/admin/">Site Administration</a></span></p>
  <p class="smaller-text">&copy; 1994 - <?php print date('Y'); ?> <a href="http://www.atlanta96foundation.org">ATLANTA 1996, Inc.</a><br />
    Atlanta, Georgia &bull; USA &bull; PHONE: 404-636-5888 &bull; FAX: 404-321-5774
  </p>
  <p><span class="site-credit">Site Design: <a href="http://www.edwardtharpdesigner.com" onclick="window.open('http://www.edwardtharpdesigner.com'); return false;">Edward Tharp Designer</a></span> <span class="site-credit">Site Development: <a href="http://www.paperstreetllc.com" onclick="window.open('http://www.paperstreetllc.com'); return false;">Paper Street LLC</a></span></p>
</div><!-- END footer -->