<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="robots" content="archive,index,cache" />
<meta name="googlebot" content="index,archive" />
<meta name="msnbot" content="index" />
<meta name="keywords" content="Olympic training facilities Atlanta 1996 Olympics international competition track and field swimming team handball tennis African Olympic training Prince Albert of Monaco Dr. Marc Daniel Gutekunst Ambassador Andrew Young" />
<meta name="description" content="The mission of the ATLANTA DITC is to provide first class training to enable participating athletes to compete in the US and internationally while furthering their education to graduate with either a high school, a vocational school, or a university degree. Athletes in training at the ATLANTA DITC prepare for the Olympic games and proudly represent their countries of origin and win Olympic Medals for their homeland." />
<meta name="MSSmartTagsPreventParsing" content="true" />
<meta name="verify-v1" content="sq1ARvGopZDc5jJMGd0tIBT67YLXauuD1mh+rANKdcU=" />
<link rel="stylesheet" type="text/css" media="screen" href="/css/base.css" />
<!--[if IE 6]>
<link rel="stylesheet" href="/css/ie6.css" media="screen"/>
<![endif]-->
<!--[if IE 7]>
<link rel="stylesheet" href="/css/ie7.css" media="screen"/>
<![endif]-->
<script type="text/javascript" src="/js/jquery-1.2.6.pack.js"></script>
<script type="text/javascript" src="/js/jquery.innerfade.js"></script>
<script type="text/javascript" src="/js/base.js"></script>
<script type="text/javascript" src="/js/swfobject.js"></script>
<script type="text/javascript">
swfobject.embedSWF("/images/ATR120x120Container.swf", "ATRswfBannerContainer", "120", "120", "5.0.0");
</script>
<script language="javascript" type="text/javascript" src="/js/tiny_mce/tiny_mce.js?v=5"></script>
<script language="javascript" type="text/javascript" src="/js/tiny_mce-rich-text.js?v=5"></script>
<link rel="stylesheet" href="/css/lightbox.css" type="text/css" media="screen" />
<script type="text/javascript" src="/js/jquery.lightbox.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	$(".lightbox").lightbox();
});
</script>
<link rel="icon" href="/favicon.ico" type="image/x-icon" />
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />