<title>ATLANTA 1996 :: The Legacy Institution of the Atlanta 1996 Centennial Olympic Games :: London 2012 WUOC House™</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="author" content="paperstreetllc.com" />
<meta name="robots" content="archive,index,cache" />
<meta name="googlebot" content="index,archive" />
<meta name="msnbot" content="index" />
<meta name="keywords" content="2012 London Olympics blog report training facilities Atlanta 1996 Olympics international competition track and field swimming team handball tennis African Olympic training Prince Albert of Monaco Dr. Marc Daniel Gutekunst Ambassador Andrew Young" />
<meta name="description" content="A blog from the 2012 Olympic Games in London U.K. from the Atlanta 1996 International Training Center who's mission is to provide first class training to enable participating athletes to compete in the US and internationally while furthering their education to graduate with either a high school, a vocational school, or a university degree. Athletes in training at the DITC prepare for the Olympic games and proudly represent their countries of origin and win Olympic Medals for their homeland." />
<meta name="MSSmartTagsPreventParsing" content="true" />
<meta name="verify-v1" content="sq1ARvGopZDc5jJMGd0tIBT67YLXauuD1mh+rANKdcU=" />
<link rel="stylesheet" type="text/css" media="screen" href="/css/base.css" />
<!--[if IE 6]>
<link rel="stylesheet" href="/css/ie6.css" media="screen"/>
<![endif]-->
<!--[if IE 7]>
<link rel="stylesheet" href="/css/ie7.css" media="screen"/>
<![endif]-->
<script type="text/javascript" src="/js/jquery-1.2.6.pack.js"></script>
<script type="text/javascript" src="/js/jquery.innerfade.js"></script>
<script type="text/javascript" src="/js/base.js"></script>
<link rel="icon" href="/favicon.ico" type="image/x-icon" />
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />