<div id="masthead">
  <h1><a href="/index.php">ATLANTA 1996 :: The Legacy Institution of the Atlanta 1996 Centennial Olympic Games</a></h1>
  <div class="clearfix">
    <a href="/london" title="London 2012 WUOC House&trade;"  id="londonBlogLink" ><img src="/images/trans-placeholder.gif" width="200" height="30" alt="London 2012 WUOC House&trade;" /></a>
    <a href="/beijing" title="&quot;Beijing Olympics&quot; Blog"  id="beijingBlogLink" ><img src="/images/trans-placeholder.gif" width="200" height="30" alt="&quot;Beijing Olympics&quot; Blog" /></a>
  </div>
</div><!-- END masthead -->