<div id="sidebar">
	<!--<a href="http://www.usteamhandballmen.org" target="_blank" id="handballRightLink"><img src="/images/calloutTHBUSOC.gif" width="150" height="155" alt="US Team Handball Men's National Team at Atlanta DITC Sponsored by the US Olympic Committee"  /></a>-->
	<!--<a href="http://www.dekalbclassic.us" target="_blank" id="dipcRightLink"><img src="/images/logo-adpc-rightbar.gif" width="150" height="155" alt="Dekalb International Prep Classic"  /></a>-->
	<a href="http://www.olympiccities.org/" target="_blank" id="WUOCRightLink"><img src="/images/wuoc_logo.png" width="150" height="155" alt="World Union of Olympic Cities"  /></a>
	<h5><a href="/competitions/"><span>Competitions</span></a></h5>
	<h5 id="partnershipsTitle">Partnerships</h5>
	<ul id="partner-logos">
		<li><a href="http://www.co.dekalb.ga.us/" target="_blank"><img src="/images/logo-DekCo-sidebar.gif" width="150" height="120" alt="Dekalb County Georgia" /></a></li>
		<li><a href="http://fnt-usa.org" target="_blank"><img src="/images/logo-FNT-sidebar.gif" width="150" height="120" alt="Forging New Tomorrows" /></a></li>
		<li><a href="http://www.anoca.info/" target="_blank"><img src="/images/logo-anoca-sidebar.gif" width="110" alt="ANOCA" /></a></li>
		<li><a href="http://www.webcaa.org/" target="_blank"><img src="/images/logo-caa-sidebar.gif" width="110" alt="CAA" /></a></li>
		<li><a href="http://www.dcvb.org/" target="_blank"><img src="/images/logo-dcvb-sidebar.gif" width="110" alt="Dekalb County Convention &amp; Visitors Bureau" height="120" /></a></li>
		<li><a href="http://www.gpc.edu/" target="_blank"><img src="/images/logo-GPC-sidebar.gif" width="150" height="120" alt="Georgia Perimeter College" /></a></li>
		<!--<li><img src="/images/logo-DekMed-sidebar.gif" width="110" alt="Dekalb Medical Center" height="120" /></li>-->
		<li><a href="http://www.emoryhealthcare.org/departments/sports/index.html" target="_blank"><img src="/images/logo-emory-sportsmedicine.gif" width="150" alt="Emory Sports Medicine Center" height="120" /></a></li>
		<li><img src="/images/logo-JaguarSports-sidebar.gif" width="110" alt="Jaguar Sports" height="120" /></li>
		<li><img src="/images/logo-USAPent-sidebar.gif" width="110" alt="USA Pentathlon" height="120" /></li>
		<li><a href="http://www.usteamhandballmen.org/" target="_blank"><img src="/images/logo-USAhandball-sidebar.gif" width="110" alt="USA Team Handball National Men Team" height="120" /></a></li>
		<li><a href="http://www.usatf.org/" target="_blank"><img src="/images/logo-USATrackField-sidebar.gif" width="110" alt="US Track &amp; Field Georgia" height="120" /></a></li>
		<!--<li><a href="http://www.usoc.org/" target="_blank"><img src="/images/logo-USOC-sidebar.gif" width="110" alt="USOC" height="120" /></a></li>-->
		<li><a href="http://www.woaolympians.com/" target="_blank"><img src="/images/logo-WOA-sidebar.gif" width="110" alt="WOA" height="120" /></a></li>
		<li><a href="http://atl96foundation.org/" target="_blank"><img src="/images/logo-ATL96Fdn-sidebar.gif" width="110" alt="Atlanta 96 Foundation" height="120" /></a></li>
		<li><a href="#" target="_blank"><img src="/images/logo-FICS-sidebar.gif" width="110" alt="FICS" height="120" /></a></li>
		<li><a href="#" target="_blank"><img src="/images/logo-SCU-sidebar.gif" width="110" alt="SCU" height="120" /></a></li>
		<li><a href="#" target="_blank"><img src="/images/logo-TAFISA-sidebar.gif" width="150" alt="TAFISA" height="120" /></a></li>
		<li><a href="#" target="_blank"><img src="/images/logo-Coventry-sidebar.gif" width="110" alt="Coventry" height="120" /></a></li>
		<li><a href="#" target="_blank"><img src="/images/logo-YALI-sidebar.gif" width="110" alt="YALI" height="120" /></a></li>
		<li><a href="#" target="_blank"><img src="/images/logo-CAU-sidebar.gif" width="110" alt="CAU" height="120" /></a></li>
		<li><a href="#" target="_blank"><img src="/images/logo-BSU-sidebar.gif" width="110" alt="BSU" height="120" /></a></li>
		<li><a href="#" target="_blank"><img src="/images/logo-BODA-sidebar.gif" width="110" alt="BODA" height="120" /></a></li>
		<li><a href="#" target="_blank"><img src="/images/logo-CONICA-sidebar.gif" width="110" alt="CONICA" height="120" /></a></li>
		<li><a href="#" target="_blank"><img src="/images/logo-JSU-sidebar.gif" width="110" alt="JSU" height="120" /></a></li>
	</ul>
	<h5 id="agreementsLink"><a href="/agreements/"><span>Official Agreements</span></a></h5>
	<div id="right-footer">&nbsp;</div>
	<p><a href="http://www.aroundtherings.com/" target="_blank" id="ATRBanner"><img src="/images/ditc_banner.gif" alt="The Dekalb International Training Center - Dekalb's Sports Authority" width="120" height="240" /></a></p>
</div>