<div id="top-nav" class="clearfix">
	<div>
		<p id="home-tnav"><a href="/index.php">Home</a></p>
		<p id="topnav-sports"><a href="/sports/cycling.php" id="cycling">Cycling</a> <a href="/sports/pentathlon.php" id="pentathlon">Pentathlon</a> <a href="/sports/swimming.php" id="swimming">Swimming</a> <a href="/sports/team-handball.php" id="handball">Team Handball</a> <a href="/sports/tennis.php" id="tennis">Tennis</a> <a href="/sports/track-field.php" id="trackfield">Track &amp; Field</a></p>
		<p id="contact-tnav"><a href="/contact">Contact Us</a></p>
	</div>
</div><!-- END top-nav -->